#!/usr/bin/env node
/**
 * discover.mjs
 * Emit a structured Phase 0 project overview for a React Native codebase:
 * flavor (Expo managed / Expo prebuild / bare RN), RN and Expo versions, the
 * new-architecture flag, TypeScript / navigation / state / styling idioms,
 * test and lint setup, tablet targeting, toolchain availability on both
 * platforms (Xcode + simulators; Android SDK + emulators — absent Android
 * means the critique degrades to iOS-only), the required-Expo-skills mapping,
 * git hooks, enforcement config, and which doc files are present. Run from
 * the project root. Analytical work (feature pattern, component conventions,
 * dark-mode readiness in source) is still done by the agent reading files.
 */
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';

function readText(path) {
  try { return readFileSync(path, 'utf8'); } catch { return ''; }
}

function readJSON(path) {
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return null; }
}

function run(cmd, args, timeout = 60000) {
  const res = spawnSync(cmd, args, { encoding: 'utf8', timeout, maxBuffer: 64 * 1024 * 1024 });
  return res.status === 0 ? (res.stdout ?? '').trim() : null;
}

// --- Package manifest ---
const pkg = readJSON('package.json');
const deps = { ...(pkg?.dependencies ?? {}), ...(pkg?.devDependencies ?? {}) };
const scripts = pkg?.scripts ?? {};
const rnVersion = deps['react-native'] ?? null;
const expoVersion = deps.expo ?? null;
const reactVersion = deps.react ?? null;
const isMonorepo = Boolean(pkg?.workspaces);

const pm = existsSync('pnpm-lock.yaml') ? 'pnpm'
  : existsSync('yarn.lock') ? 'yarn'
    : (existsSync('bun.lockb') || existsSync('bun.lock')) ? 'bun'
      : 'npm';
const pmNote = (pm === 'npm' && !existsSync('package-lock.json')) ? ' (no lockfile found)' : '';

// --- Flavor: Expo managed (CNG) / Expo prebuild / bare RN ---
const hasIosDir = existsSync('ios');
const hasAndroidDir = existsSync('android');
const flavor = !pkg || (!rnVersion && !expoVersion)
  ? 'not a React Native project (no react-native or expo dependency)'
  : expoVersion && !hasIosDir && !hasAndroidDir
    ? 'Expo managed (CNG — native dirs generated by expo run / prebuild)'
    : expoVersion
      ? 'Expo prebuild (expo dependency with checked-in native dirs)'
      : (hasIosDir || hasAndroidDir)
        ? 'bare React Native'
        : 'unknown (react-native dependency but no native dirs — a library?)';

// --- App config (Expo): app.json / app.config.json are statically readable ---
const appConfig = readJSON('app.json')?.expo ?? readJSON('app.config.json')?.expo ?? null;
const dynamicConfig = ['app.config.js', 'app.config.ts'].find((p) => existsSync(p)) ?? null;

// --- New architecture ---
// RN >= 0.76 defaults the new architecture ON; an explicit flag wins.
const gradleProps = readText('android/gradle.properties');
const podfileProps = readJSON('ios/Podfile.properties.json');
const newArchFlag =
  gradleProps.match(/^newArchEnabled\s*=\s*(true|false)/m)?.[1]
  ?? (typeof podfileProps?.newArchEnabled === 'string' ? podfileProps.newArchEnabled : null)
  ?? (typeof appConfig?.newArchEnabled === 'boolean' ? String(appConfig.newArchEnabled) : null);
const newArch = newArchFlag
  ? `${newArchFlag} (explicit)`
  : 'not set (RN ≥ 0.76 defaults to enabled)';

// --- Language / navigation / state / styling idioms ---
const hasTypescript = existsSync('tsconfig.json') || Boolean(deps.typescript);
const navigation = deps['expo-router']
  ? `expo-router (file-based routes under ${existsSync('app') ? '`app/`' : 'its routes dir'})`
  : deps['@react-navigation/native']
    ? 'react-navigation'
    : 'none detected';
const stateLibs = ['@reduxjs/toolkit', 'redux', 'zustand', 'mobx', 'jotai', 'recoil', '@tanstack/react-query', 'swr']
  .filter((d) => deps[d]);
const stylingLibs = ['nativewind', 'tamagui', '@shopify/restyle', 'styled-components', '@emotion/native']
  .filter((d) => deps[d]);
const styling = stylingLibs.length ? stylingLibs.join(', ') : 'StyleSheet (no styling library detected)';

// --- Tests ---
const jestConfigured = Boolean(deps.jest) || existsSync('jest.config.js') || existsSync('jest.config.ts') || Boolean(pkg?.jest)
  || /\bjest\b/.test(scripts.test ?? '');
const hasRtl = Boolean(deps['@testing-library/react-native']);
const hasDetox = Boolean(deps.detox) || existsSync('.detoxrc.js') || existsSync('.detoxrc.json');
const hasMaestro = existsSync('.maestro');

// --- Lint / format config ---
const eslintConfig = [
  'eslint.config.js', 'eslint.config.mjs', 'eslint.config.cjs', 'eslint.config.ts',
  '.eslintrc.js', '.eslintrc.cjs', '.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc',
].find((p) => existsSync(p));
const prettierConfig = ['.prettierrc', '.prettierrc.js', '.prettierrc.json', '.prettierrc.yml', 'prettier.config.js']
  .find((p) => existsSync(p)) ?? (pkg?.prettier ? 'package.json "prettier"' : null);

// --- Tablet targeting ---
const iosProjects = hasIosDir
  ? (() => { try { return readdirSync('ios').filter((e) => e.endsWith('.xcodeproj')); } catch { return []; } })()
  : [];
const pbxproj = iosProjects.length ? readText(join('ios', iosProjects[0], 'project.pbxproj')) : '';
const deviceFamily = [...new Set([...pbxproj.matchAll(/TARGETED_DEVICE_FAMILY\s*=\s*"?([^";]+)"?;/g)].map((m) => m[1].trim()))].join(', ') || null;
const supportsTablet = appConfig?.ios?.supportsTablet === true
  || (deviceFamily ? deviceFamily.includes('2') : false);

// --- Toolchain: shared, iOS half (darwin only), Android half ---
const nodeVersion = process.version;
const hasWatchman = spawnSync(process.platform === 'win32' ? 'where' : 'which', ['watchman'], { encoding: 'utf8' }).status === 0;

const isDarwin = process.platform === 'darwin';
const xcodePath = isDarwin ? run('xcode-select', ['-p'], 10000) : null;
const xcodeVersion = isDarwin ? run('xcodebuild', ['-version'], 30000)?.replace(/\n/g, ' — ') : null;
let runtimes = [];
let simDevices = [];
if (isDarwin) {
  const simList = run('xcrun', ['simctl', 'list', '-j'], 30000);
  if (simList) {
    try {
      const parsed = JSON.parse(simList);
      runtimes = (parsed.runtimes ?? []).filter((r) => r.isAvailable && /iOS/.test(r.name)).map((r) => r.name);
      for (const [runtimeId, devices] of Object.entries(parsed.devices ?? {})) {
        if (!/iOS/.test(runtimeId)) continue;
        for (const d of devices) {
          if (d.isAvailable) simDevices.push(`${d.name} (${d.state})`);
        }
      }
    } catch { /* unparseable */ }
  }
}
const podVersion = (isDarwin && (hasIosDir || flavor.startsWith('Expo managed'))) ? run('pod', ['--version'], 30000) : null;

// Android SDK: env var or adb/emulator on PATH. Absent SDK is not an error —
// the critique degrades to iOS-only.
const sdkRoot = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT || null;
const adbBin = spawnSync(process.platform === 'win32' ? 'where' : 'which', ['adb'], { encoding: 'utf8' }).status === 0
  ? 'adb'
  : (sdkRoot && existsSync(join(sdkRoot, 'platform-tools', 'adb')) ? join(sdkRoot, 'platform-tools', 'adb') : null);
const emulatorBin = spawnSync(process.platform === 'win32' ? 'where' : 'which', ['emulator'], { encoding: 'utf8' }).status === 0
  ? 'emulator'
  : (sdkRoot && existsSync(join(sdkRoot, 'emulator', 'emulator')) ? join(sdkRoot, 'emulator', 'emulator') : null);
const avds = emulatorBin ? (run(emulatorBin, ['-list-avds'], 30000) ?? '').split('\n').filter((l) => l.trim() && !l.startsWith('INFO')) : [];
const runningAndroid = adbBin
  ? (run(adbBin, ['devices'], 15000) ?? '').split('\n').slice(1)
      .map((l) => l.trim().split(/\s+/))
      .filter((p) => p.length >= 2 && p[1] === 'device')
      .map((p) => p[0])
  : [];
const androidAvailable = Boolean(adbBin && (avds.length || runningAndroid.length));

// --- Design language ---
// The project's own design system wins; absent one, each platform's idiom is
// the default (HIG on iOS, Material on Android). Heuristic: a styling library
// with a token system, or a theme/design-system module.
const themeDirs = ['src/theme', 'src/design-system', 'theme', 'design-system', 'src/styles/tokens']
  .filter((d) => existsSync(d));
const tamaguiConfig = ['tamagui.config.ts', 'tamagui.config.js'].find((p) => existsSync(p));
const tailwindConfig = ['tailwind.config.js', 'tailwind.config.ts'].find((p) => existsSync(p));
const hasDesignSystem = Boolean(tamaguiConfig || (deps.nativewind && tailwindConfig) || deps['@shopify/restyle'] || themeDirs.length);
const designLanguage = hasDesignSystem
  ? `project design system (${[tamaguiConfig, deps.nativewind && tailwindConfig ? 'nativewind + tailwind config' : null, deps['@shopify/restyle'] ? '@shopify/restyle' : null, ...themeDirs].filter(Boolean).join(', ')}) — it wins over platform defaults`
  : 'platform defaults — HIG idiom on iOS, Material idiom on Android';
const hasSafeArea = Boolean(deps['react-native-safe-area-context']);

// --- Required Expo skills (Expo flavor only) ---
// Only the skills the project's detected usage requires — never the full
// catalog. eas-* and the specialized skills are never in the required set.
let expoSkills = null;
if (expoVersion) {
  const required = [];
  if (deps['expo-router']) required.push(['expo-router', 'expo-router dependency detected']);
  if (deps['@expo/ui']) required.push(['expo-ui', '@expo/ui dependency detected']);
  if (deps.nativewind && !tailwindConfig) required.push(['expo-tailwind-setup', 'nativewind dependency without a tailwind config (setup-shaped gap)']);
  if (!hasDesignSystem) required.push(['expo-native-ui', 'no project design system — platform-idiom (HIG) styling is the default']);
  if (['@tanstack/react-query', 'swr', 'axios'].some((d) => deps[d])) {
    required.push(['expo-data-fetching', 'a data-fetching stack is in use']);
  }
  const installed = existsSync('.claude/skills')
    ? (() => { try { return readdirSync('.claude/skills').filter((d) => d.startsWith('expo-') || d.startsWith('eas-')); } catch { return []; } })()
    : [];
  expoSkills = { required, installed, missing: required.filter(([name]) => !installed.includes(name)) };
}

// --- Inferred default gates (what gates.mjs will run without an override) ---
const inferredGates = (pkg && (rnVersion || expoVersion))
  ? [
      ...(scripts.typecheck || scripts['type-check'] ? [`\`${pm} run ${scripts.typecheck ? 'typecheck' : 'type-check'}\``]
        : hasTypescript && existsSync('tsconfig.json') ? ['`npx tsc --noEmit`'] : []),
      ...(scripts.lint ? [`\`${pm} run lint\``] : eslintConfig ? ['`npx eslint .`'] : []),
      ...(scripts.test ? [`\`${pm} run test\`` + (/--watch/.test(scripts.test) ? ' (watch guard appended)' : '')] : []),
      '(native iOS/Android builds are not default gates — Phase 4 device start builds both; pin them in gates.json to gate on them)',
    ]
  : ['none inferable — pin commands in .cache/develop-react-native-feature/gates.json'];

// --- Git hooks ---
const hooks = [];
for (const dir of ['.githooks', '.git/hooks', '.husky']) {
  if (existsSync(dir)) {
    try {
      readdirSync(dir).filter((f) => !f.endsWith('.sample') && !f.startsWith('_') && !f.startsWith('.')).forEach((f) => hooks.push(`${dir}/${f}`));
    } catch { /* ignore */ }
  }
}

// --- .claude/settings.json enforcement ---
const settings = readJSON('.claude/settings.json');
const preHooks = (settings?.hooks?.PreToolUse ?? [])
  .flatMap((h) => (h.hooks ?? []).map((hk) => hk.command));
const allowList = settings?.permissions?.allow ?? [];

// --- Docs ---
const DOCS = ['CLAUDE.md', 'AGENTS.md', 'README.md', 'CONTRIBUTING.md', 'DESIGN.md'];

// --- Output ---
const lines = [
  '## Project Discovery',
  '',
  `**Flavor:** ${flavor}`,
  `**react-native:** ${rnVersion ?? 'not a dependency'}${expoVersion ? ` — **expo:** ${expoVersion}` : ''} — **react:** ${reactVersion ?? '?'}`,
  `**Package manager:** ${pm}${pmNote}${isMonorepo ? ' (workspaces — a monorepo; run from the app package root)' : ''}`,
  `**New architecture:** ${newArch}`,
  `**TypeScript:** ${hasTypescript ? 'yes' : 'no'}`,
  `**Navigation:** ${navigation}`,
  `**State management:** ${stateLibs.length ? stateLibs.join(', ') : 'none detected (component state / context)'}`,
  `**Styling:** ${styling}`,
  `**Tablet (iPad) targeted:** ${supportsTablet ? 'yes' : 'no'}${deviceFamily ? ` (TARGETED_DEVICE_FAMILY = ${deviceFamily})` : appConfig?.ios ? ' (expo.ios.supportsTablet)' : ''}`,
  ...(dynamicConfig ? [`**Note:** ${dynamicConfig} is dynamic — read it for config the static scan cannot see.`] : []),
  '',
  '### Inferred Gates (gates.mjs defaults)',
  ...inferredGates.map((g) => `- ${g}`),
  '',
  '### Tests',
  `- jest: ${jestConfigured ? 'configured' : 'not detected'}`,
  `- @testing-library/react-native: ${hasRtl ? 'yes' : 'not detected'}`,
  `- detox (e2e): ${hasDetox ? 'yes' : 'not detected'}`,
  `- maestro (e2e): ${hasMaestro ? 'yes (.maestro/)' : 'not detected'}`,
  '',
  '### Design language',
  `- ${designLanguage}`,
  `- safe-area handling: ${hasSafeArea ? 'react-native-safe-area-context installed' : 'react-native-safe-area-context NOT installed — verify how insets are handled'}`,
  '- dark-mode readiness: verify while reading source (useColorScheme / theme dark variants)',
  ...(expoSkills
    ? [
        '',
        '### Required Expo skills (detection-driven — never the full catalog)',
        ...(expoSkills.required.length
          ? expoSkills.required.map(([name, why]) => `- \`${name}\` — ${why}${expoSkills.installed.includes(name) ? ' — INSTALLED' : ' — missing'}`)
          : ['- none required by detected usage']),
        ...(expoSkills.installed.filter((s) => !expoSkills.required.some(([n]) => n === s)).length
          ? [`- also installed (not in the required set): ${expoSkills.installed.filter((s) => !expoSkills.required.some(([n]) => n === s)).join(', ')}`]
          : []),
        `- install a missing one with: \`npx skills add expo/skills --skill <name>\``,
        '- expo-data-fetching also joins the required set when the shaped feature touches remote data (a Phase 1 fact)',
      ]
    : []),
  '',
  '### Lint / format',
  eslintConfig ? `- ESLint config: \`${eslintConfig}\`` : '- no ESLint config; lint gate skipped unless pinned via gates.json',
  prettierConfig ? `- Prettier config: \`${prettierConfig}\` (a gate only via an explicit check-shaped script)` : '- no Prettier config',
  '',
  '### Toolchain',
  `- node: ${nodeVersion}`,
  `- watchman: ${hasWatchman ? 'on PATH' : 'not installed (optional accelerator)'}`,
  ...(isDarwin
    ? [
        `- xcode-select -p: ${xcodePath ?? 'FAILED — is Xcode installed and selected?'}`,
        `- xcodebuild: ${xcodeVersion ?? 'unavailable'}`,
        `- iOS simulator runtimes: ${runtimes.length ? runtimes.join(', ') : 'none available'}`,
        `- simulator devices: ${simDevices.length ? simDevices.slice(0, 12).join('; ') : 'none available'}`,
        ...(podVersion !== null || hasIosDir ? [`- CocoaPods: ${podVersion ?? 'NOT installed — needed before an ios/ build (pod install)'}`] : []),
      ]
    : ['- not macOS — the iOS half of the critique is unavailable on this machine']),
  `- Android SDK: ${sdkRoot ?? (adbBin ? 'not set (adb found on PATH)' : 'NOT detected (ANDROID_HOME/ANDROID_SDK_ROOT unset, no adb)')}`,
  ...(adbBin
    ? [
        `- AVDs: ${avds.length ? avds.join(', ') : 'none created'}`,
        `- running Android devices/emulators: ${runningAndroid.length ? runningAndroid.join(', ') : 'none'}`,
      ]
    : []),
  ...(androidAvailable ? [] : ['- **Android critique degrades to iOS-only on this machine** — noted in the critique snapshot']),
  '',
  '### Git Hooks',
  ...(hooks.length ? hooks.map((h) => `- \`${h}\``) : ['- none found']),
  '',
  '### Enforcement (.claude/settings.json)',
  ...(preHooks.length
    ? ['PreToolUse hooks:', ...preHooks.map((h) => `  - \`${h}\``)]
    : ['- no PreToolUse hooks configured']),
  ...(allowList.length
    ? ['Allow list:', ...allowList.map((e) => `  - \`${e}\``)]
    : []),
  '',
  '### Docs',
  ...DOCS.map((d) => `- ${d}: ${existsSync(d) ? '✓' : '✗'}`),
];

console.log(lines.join('\n'));
